### ISSUE TITLE
Invalid Files cause script to crash

### ISSUE THREAD

**Issue by RealDyllon** [leafgecko/NTULearn-Downloader#8]
Child HTML Element of contentList.children below causes the script to crash:

```html
<li class="clearfix liItem read" id="contentListItem:_2403613_1">
<img alt="File" class="item_icon" src="/images/ci/sets/set12/file_on.svg"/>
<div class="item clearfix" id="_2403613_1">
<h3>
<span class="reorder editmode hideme"><span><img alt="" src="/images/ci/icons/generic_updown.gif"/></span></span>
<span style="color:#000000;">Course schedule for CX1104, 2020-2021, Sem2 (Invalid File)</span>
</h3>
</div>
<div class="details">
<div class="alignPanel"> <div id="LEARNING_STANDARD_blackboard.data.content.Content;_2403613_1"> </div> </div>
</div>
<div class="moduleSample" id="_2403613_1previewModule">
</div>
</li>
```

The above html snippet doesn't contain an `<a>` tag, creating an uncaught error:

```bash
Traceback (most recent call last):
  File "/Users/dyllon/NTULearn-Downloader/main.py", line 190, in <module>
    course_folder = get_download_dir(bbrouter, name, course_id)
  File "/Users/dyllon/NTULearn-Downloader/ntu_learn_downloader/api.py", line 279, in get_download_dir
    children = [
  File "/Users/dyllon/NTULearn-Downloader/ntu_learn_downloader/api.py", line 284, in <listcomp>
    children=get_contents(BbRouter, course_id, content_id),
  File "/Users/dyllon/NTULearn-Downloader/ntu_learn_downloader/api.py", line 194, in get_contents
    children = [to_model(c) for c in parse_content_page(soup)]
  File "/Users/dyllon/NTULearn-Downloader/ntu_learn_downloader/parsing.py", line 72, in parse_content_page
    name = hyperlink.text
AttributeError: 'NoneType' object has no attribute 'text'
```
I'll PR a fix soon.

**Comment by RealDyllon** [comment]
I've created #9.
